News/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls, name='admin'),
   path('accounts/', include('allauth.urls')),
   # path("accounts/", include("accounts.urls")),
   path('pages/', include('django.contrib.flatpages.urls')),
   # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
   # подключались к главному приложению с префиксом products/.
   path('news/', include('newsportal.urls')),
   path('articles/', include('newsportal.urls')),
]

newsportal/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.authorUser.username}'

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat *3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return f'{self.name}'



class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новости'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def __str__(self):
        return f'{self.title}: {self.text[:10]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


# class Subscription(models.Model):
#     user = models.ForeignKey(
#         to=User,
#         on_delete=models.CASCADE,
#         related_name='subscriptions',
#     )
#     category = models.ForeignKey(
#         to='Category',
#         on_delete=models.CASCADE,
#         related_name='subscriptions',
#     )

templates/category_list.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}


{% block title %}
Post
{% endblock title %}


{% block content %}
    <div class="btn-group">
    <form><a href="http://127.0.0.1:8000/accounts/signup/"><input type="button" value="Регистрация" /></a></form>
        <form><a href="http://127.0.0.1:8000/accounts/logout/"><input type="button" value="Выйти" /></a></form>
    </div>
  <h1><font color="red">Все новости</font></h1>
   <h3><font color="orange">Количество статей/новостей:{{ news_content|length }}</font></h3>
   <h3>Сегодня: {% current_time '%d %b %Y %A' %}</h3>
    <h3><font color="green">Публикации</font></h3>



    <hr>
    {% if category_news_list %}
    <h4>
        {% if perms.newsportal.add_post %}
    <form><a href="{% url 'news_create' %}"><input type="button" value="Создать публикацию" /></a></form>
        {% endif %}
    </h4>
    <h4>
    <form><a href="{% url 'news_list' %}"><input type="button" value="Вернуться на главную" /></a></form>
    </h4>
    <h5>
    <form><a href="{% url 'post_search' %}"><input type="button" value="Поиск" /></a></form>
    </h5>
    <h5>
      {% if is_not_subscriber %}
    <p><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
      {% endif %}
    </h5>
    <hr>
    <h5><font color="blue">Все публикации:</font></h5>
       <table>
           <tr>
               <td>Название статьи или новости</td>
               <td>Раздел</td>
               <td>Автор</td>
               <td>Текст статьи или новости</td>
               <td>Дата публикации</td>
                <td>Рейтинг</td>

               {# Условие получается составным. #}
                {% if perms.newsportal.change_post or perms.newsportal.delete_post %}
                <td>Редактирование</td>
                {% endif %}

           <tr>
           {% for Post in category_news_list %}
           <tr>
               <td>
                   <a href="{% url 'news_detail' pk=Post.id %}">{{ Post.title|censor }}</a>
               </td>
               <td>

                     {% for category in Post.postCategory.all %}
                     <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                     {% endfor %}

               </td>
               <td>{{ Post.author.authorUser }}</td>
               <td>{{ Post.text|truncatechars:20 }}</td>
               <td>{{ Post.dateCreation|date:'d M Y ' }}</td>
                <td>{{ Post.rating }}</td>
                <td>

                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.newsportal.change_post %}
                    <a href="{% url 'news_update' pk=Post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.newsportal.delete_post %}
                    <a href="{% url 'post_delete' pk=Post.id %}">Удалить</a>
                    {% endif %}
                </td>

          <tr>
           {% endfor %}
       </table>
    {% else %}
       <h2>Публикаций нет!</h2>
    {% endif %}


    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

    <hr>
    <h7>PythonDjangoPost</h7>


{% endblock content %}

templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Приветствуем! Новые публикации за неделю.</h2>
<ul>
  {% for post in posts %}
  <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

templates/news.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}


{% block title %}
Post
{% endblock title %}


{% block content %}
    <div class="btn-group">
    <form><a href="http://127.0.0.1:8000/accounts/signup/" class="btn btn-primary">Регистрация</a></form>
        <form><a href="http://127.0.0.1:8000/accounts/logout/" class="btn btn-info">Выйти</a></form>
    </div>
  <h1><font color="red">Все новости</font></h1>
   <h3><font color="orange">Количество статей/новостей:{{ news_content|length }}</font></h3>
   <h3>Сегодня: {% current_time '%d %b %Y %A' %}</h3>
    <h3><font color="green">Публикации</font></h3>



    <hr>
    {% if news_content %}
    <h4>
        {% if perms.newsportal.add_post %}
    <form><a href="{% url 'news_create' %}" class="btn btn-secondary btn-sm">Создать публикацию</a></form>
        {% endif %}
    </h4>
    <h5>
    <p><a href="{% url 'post_search' %}" class="btn btn-secondary btn-sm">Поиск</a></p>
    </h5>
    <h5>
      {% if is_not_subscriber %}
    <p><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
      {% endif %}
    </h5>
    <hr>
    <h5><font color="blue">Все публикации:</font></h5>
       <table>
           <tr>
               <td>Название статьи или новости</td>
               <td>Категории</td>
               <td>Автор</td>
               <td>Текст статьи или новости</td>
               <td>Дата публикации</td>
                <td>Рейтинг</td>

               {# Условие получается составным. #}
                {% if perms.newsportal.change_post or perms.newsportal.delete_post %}
                <td>Редактирование</td>
                {% endif %}

           <tr>
           {% for Post in news_content %}
           <tr>
               <td>
                   <a href="{% url 'news_detail' pk=Post.id %}">{{ Post.title|censor }}</a>
               </td>
               <td>
                   {% for category in Post.postCategory.all %}
                     <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                   {% endfor %}
               </td>
               <td>{{ Post.author.authorUser }}</td>
               <td>{{ Post.text|truncatechars:20 }}</td>
               <td>{{ Post.dateCreation|date:'d M Y ' }}</td>
                <td>{{ Post.rating }}</td>
                <td>

                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.newsportal.change_post %}
                    <a href="{% url 'news_update' pk=Post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.newsportal.delete_post %}
                    <a href="{% url 'post_delete' pk=Post.id %}">Удалить</a>
                    {% endif %}
                </td>

          <tr>
           {% endfor %}
       </table>
    {% else %}
       <h2>Публикаций нет!</h2>
    {% endif %}


    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

    <hr>
    <h7>PythonDjangoPost</h7>


{% endblock content %}

templates/post_create_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Приветствуем! Новая <a href="{{ link }}"> публикация в твоей подписке</a></h2>
<p>{{ text }}</p>
</body>
</html>

templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}


{% block content %}
<h1><font color="red">Удаление публикации</font></h1>
<hr>
    <h4>
    <form><a href="{% url 'news_list' %}"><input type="button" value="Вернуться на главную" /></a></form>
    </h4>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p><h7><font color="blue">Загаловок:</font></h7><br>"{{ object.title }}"<br>
    <h7><font color="blue">Текст: </font></h7><br> "{{ object.text }}" ?</p>
    <input type="submit" value="Удалить" />
</form>

<hr>
    <h7>PythonDjangoPost</h7>

{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1><font color="green">Работа с публикацией</font></h1>
<hr>
    <h4>
    <form><a href="{% url 'news_list' %}"><input type="button" value="Вернуться на главную" /></a></form>
    </h4>
<hr>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

<hr>
    <h7>PythonDjangoPost</h7>

{% endblock content %}

templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1><font color="red">Все новости</font></h1>
<h3><font color="orange">Количество статей/новостей:{{ post_search|length }}</font></h3>
   <h3>Сегодня: {% current_time '%d %b %Y %A' %}</h3>
<hr>
    <h4>
    <form><a href="{% url 'news_list' %}"><input type="button" value="Вернуться на главную" /></a></form>
    </h4>
<hr>
    <h3><font color="red">Поиск публикаций по параметрам:</font></h3>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Поиск" />
   </form>

    <hr>
    <h5><font color="blue">Все публикации:</font></h5>
    {% if post_search %}
       <table>
           <tr>
               <td>Название статьи или новости</td>
               <td>Раздел</td>
               <td>Автор</td>
               <td>Текст статьи или новости</td>
               <td>Дата публикации</td>
                <td>Рейтинг</td>
           <tr>
           {% for Post in post_search %}
           <tr>
               <td>
                   <a href="{% url 'news_detail' pk=Post.id %}">{{ Post.title|censor }}</a>
               </td>
               <td>{{ Post.categoryType }}</td>
               <td>{{ Post.author.authorUser }}</td>
               <td>{{ Post.text|truncatechars:20 }}</td>
               <td>{{ Post.dateCreation|date:'d M Y ' }}</td>
                <td>{{ Post.rating }}</td>
          <tr>
           {% endfor %}
       </table>
    {% else %}
       <h2>Публикаций нет!</h2>
    {% endif %}



    {% if page_obj.has_previous %}
       {# Для каждой ссылки пагинации указываем обработку через новый тег #}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

<hr>
    <h7>PythonDjangoPost</h7>

{% endblock content %}

templates/selected_news.html
<!--  наследуемся от шаблона default.html -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1><font color="red">Мировые новости</font></h1>
<h1><font color="blue">Публикация</font></h1>
<h1><font color="orange">(AR)Статья/(NW)Новости</font></h1>
<h3><i>Сегодня: {% current_time '%d %b %Y %A' %}</i></h3>
<hr>
    <h4>
    <form><a href="{% url 'news_list' %}"><input type="button" value="Вернуться на главную" /></a></form>
    </h4>
<hr>
    <table>
        <tr>
            <td><b>Загаловок</b></td>
            <td><b>Текст</b></td>
            <td><b>Дата публикации</b></td>
            <td><b>Раздел</b></td>
            <td><b>Автор</b></td>
            <td><b>Рейтинг</b></td>
        <tr>

        <tr>
            <td>{{ selected_news.title|censor }}</td>
            <td>
                <div align="center">{{ selected_news.text|censor }}</div>
            </td>
            <td>{{ selected_news.dateCreation|date:'d M Y ' }}</td>
            <td>{{ selected_news.categoryType }}</td>
            <td>{{ selected_news.author.authorUser }}</td>
            <td>{{ selected_news.rating }}</td>
        </tr>
    </table>
<hr>
    <h7>PythonDjangoPost</h7>

{% endblock content %}

templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}


{% block content %}
<h1><font color="red">Подписка</font></h1>
<hr>
    <h4>
    <form><a href="{% url 'news_list' %}"><input type="button" value="Вернуться на главную" /></a></form>
    </h4>
<hr>
  <h1 class="text-center">{{ message }} {{ category }}</h1>
<hr>
    <h7>PythonDjangoPost</h7>

{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    <h4>
    <form><a href="{% url 'news_list' %}"><input type="button" value="Вернуться на главную" /></a></form>
    </h4>
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}